import type { Metadata } from "next";
import { Inter, Kantumruy_Pro } from "next/font/google";
import "./globals.css";
import NavbarCom from "@/components/NavbarCom"
import { Providers } from "./provider";
import FooterCom from "@/components/FooterCom";
const inter = Inter({ subsets: ["latin"] });
const kantumruy = Kantumruy_Pro({
  subsets: ["khmer"],
  weight: ["300", "400", "700"],
  display: "swap",
  style: ['italic', 'normal'],
  variable: '--font-kantumruy-pro'
});

export const metadata: Metadata = {
  title: "Commerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={kantumruy.className}>
          <Providers>
            <NavbarCom/>
            {children}
            <FooterCom/>
        </Providers>
      </body>
    </html>
  );
}
